apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: polinux/stress
        name: mem-stress
        args:
          - --vm
          - "1"
          - --vm-bytes
          - 495M
          - --vm-hang
          - "1"
        command:
          - stress
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 200Mi