apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      memory: 400Mi
    defaultRequest: # this section defines default requests
      memory: 150Mi
    type: Container
